name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spree:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/spree:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/spree:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spree:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/spree:${{ github.sha }}
          cd /opt/spree
          export COMMIT_SHA=${{ github.sha }}
          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d